
# This file was generated by the SOM Compiler.
# FileName: BlackHol.sc.
# Generated using:
#     SOM Precompiler spc: 1.22
#     SOM Emitter emitcsc: 1.10

/*
 * 
 *   DMan.CSC - Workplace Shell test
 * ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
 * ³  Greg's Black Hole - anything you put in will disappear forever...  ³
 * ³                                                                     ³
 * ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿   Gregory Czaja, CONT00 @ LEXVMK, November 1992  ³
 *                    ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
 */

#include "wpabs.sc"

class: BlackHole, 
    external stem = BlackHol, local, external prefix = BlackHolX_, 
    classprefix = BlackHolC_, major version = 1, minor version = 1, 
    file stem = BlackHol;


parent class: WPAbstract;


passthru: C.h, after;
 /* public defs for BlackHole */
endpassthru;
methods:


    override wpDragOver;

    -- From WPObject

    override wpDrop;

    -- From WPObject

    override wpclsInitData, class;

    -- From WPObject

    override wpclsUnInitData, class;

    -- From WPObject

