
/*
 * This file was generated by the SOM Compiler.
 * FileName: BlackHol.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

/*
 * 
 * 
 *   DMan.CSC - Workplace Shell test
 * ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
 * ³  Greg's Black Hole - anything you put in will disappear forever...  ³
 * ³                                                                     ³
 * ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿   Gregory Czaja, CONT00 @ LEXVMK, November 1992  ³
 *                    ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
 */


#ifndef BlackHol_h
#define BlackHol_h


#include <som.h>

/*
 * Define the class name as an object type
 */
#ifndef BlackHole
#define BlackHole SOMAny
#endif
#include "wpabs.h"

/*
 * Passthru lines: File: "C.h", "after"
 */
/* public defs for BlackHole */

#define BlackHole_MajorVersion 1
#define BlackHole_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define BlackHoleNewClass BlackHolc
#pragma linkage(BlackHolc, system)
#define BlackHoleClassData BlackHold
#define BlackHoleCClassData BlackHolx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define BlackHole_classObj BlackHoleClassData.classObject
#define _BlackHole BlackHole_classObj

/*
 * New and Renew macros for BlackHole
 */
#define _BlackHoleNew() (_somNew(BlackHoleClassData.classObject))
#define BlackHoleNew() \
	( BlackHoleClassData.classObject \
		? _BlackHoleNew() \
		: ( BlackHoleNewClass(BlackHole_MajorVersion, BlackHole_MinorVersion), _BlackHoleNew() ) )
#define BlackHoleRenew(buf) \
	( _somRenew(BlackHoleClassData.classObject, buf) )

/*
 * Override method: wpDragOver
 */
#define BlackHole_wpDragOver(somSelf,hwndCnr,pdrgInfo) \
	WPObject_wpDragOver(somSelf,hwndCnr,pdrgInfo)

/*
 * Override method: wpDrop
 */
#define BlackHole_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem) \
	WPObject_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem)

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK BlackHoleNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(BlackHoleNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct BlackHoleClassDataStructure {
	SOMAny *classObject;
} BlackHoleClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct BlackHoleCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} BlackHoleCClassData;

#endif       /* BlackHol_h */

/*
 * This file was generated by the SOM Compiler.
 * FileName: BlackHol.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

#ifndef BlackHol_mh
#define BlackHol_mh


/*
 * Define the class name as an object type
 */
#ifndef M_BlackHole
#define M_BlackHole SOMAny
#endif

#define M_BlackHole_MajorVersion 1
#define M_BlackHole_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_BlackHoleNewClass BlackHolc
#pragma linkage(BlackHolc, system)
#define M_BlackHoleClassData BlackHold
#define M_BlackHoleCClassData BlackHolx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_BlackHole_classObj M_BlackHoleClassData.classObject
#define _M_BlackHole M_BlackHole_classObj

/*
 * New and Renew macros for M_BlackHole
 */
#define _M_BlackHoleNew() (_somNew(M_BlackHoleClassData.classObject))
#define M_BlackHoleNew() \
	( M_BlackHoleClassData.classObject \
		? _M_BlackHoleNew() \
		: ( M_BlackHoleNewClass(M_BlackHole_MajorVersion, M_BlackHole_MinorVersion), _M_BlackHoleNew() ) )
#define M_BlackHoleRenew(buf) \
	( _somRenew(M_BlackHoleClassData.classObject, buf) )

/*
 * Override method: wpclsInitData
 */
#define M_BlackHole_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_BlackHole_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK M_BlackHoleNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(M_BlackHoleNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_BlackHoleClassDataStructure {
	SOMAny *classObject;
} M_BlackHoleClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_BlackHoleCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} M_BlackHoleCClassData;

#endif       /* BlackHol_h */
