
/*
 * This file was generated by the SOM Compiler.
 * FileName: BlackHol.ph.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitph: 1.10
 */

/*
 * 
 * 
 *   DMan.CSC - Workplace Shell test
 * ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
 * ³  Greg's Black Hole - anything you put in will disappear forever...  ³
 * ³                                                                     ³
 * ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿   Gregory Czaja, CONT00 @ LEXVMK, November 1992  ³
 *                    ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
 */


#ifndef BlackHol_ph
#define BlackHol_ph


/*
 * Passthru lines: File: "C.ph", "before"
 */
/* private defs for BlackHole */

#include "BlackHol.h"

/*
 * Include any needed private header files
 */

#endif       /* BlackHol_ph */

/*
 * This file was generated by the SOM Compiler.
 * FileName: BlackHol.ph.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitph: 1.10
 */

#ifndef BlackHol_mph
#define BlackHol_mph


/*
 * Include any needed private header files
 */

#endif       /* BlackHol_ph */
